from src.tg_bot.utils.states import UserState
from src.tg_bot.utils.text_constants import INITIAL_STATE_MESSAGES, UNAUTHORIZED_STATE_MESSAGES, AUTH_WAITING_MESSAGES, AUTHORIZED_STATE_MESSAGES, RESUME_PREPARATION_MESSAGES, RESUME_PREPARATION_MESSAGES
from src.tg_bot.utils.keyboards import auth_keyboard, start_keyboard, auth_waiting_keyboard, authorized_keyboard, resume_preparation_keyboard